### ISSUE TITLE
Python package multi config not separate

### ISSUE THREAD

**Issue by marco-bazzani** [UCSD-E4E/acoustic-multiclass-training#110]
Ask ben for details

**Comment by benjamin-cates** [comment]
So basically the problem right now is that when you run `pip install -e .` it stores a reference to that repository in your conda site-packages. When trying to run a different instance of the repository on the same user, it references the other config. I think the best way forward is to print out which config is being referenced and add a command line argument to specify which config to use.

**Comment by benjamin-cates** [comment]
Hmmm it seems like we would have to refactor a lot of `config.py` in order to parse a config argument because you can't init two argparse objects in the same program. Also had difficulty printing out the config path because it's called every time a new worker is spawned. I guess a good solution is to have it search for a local config first and default to wherever the package says the config is after that.

**Comment by benjamin-cates** [comment]
Fixed with bf89c5acc5a05a68fc34b71b716be974e39afb4e
